### PR TITLE
Fix option collision error rendering

### LINKED ISSUE #248: | conbinator calls toString on objects with default toString implementation
`a.map(...) | b.map(...)` produces a strange error message which includes `toString` of `Function`:

```scala
  private val a = Options.text("a").map(identity)
  private val b = Options.text("b").map(identity)

      command = Command("test", a | b),
```

```sh
 $ ./bin/test -a a -b b
Options collision detected. You can only specify either
Map(Single(a,Vector(),Text,Empty,None),zio.cli.Options$$Lambda$16/0x0000000800cc
13e0@37b3bd45) or
Map(Single(b,Vector(),Text,Empty,None),zio.cli.Options$$Lambda$16/0x0000000800cc
13e0@56d5379).
```

See minimal reproducer here: https://github.com/senia-psm/zio-cli-248

### PR DESCRIPTION
**Pull request by kitlangton**
Closes #248  (/claim #248)

I also deleted a couple of old, unused methods/comments.

### CODE REVIEW

File: zio-cli/shared/src/main/scala/zio/cli/Options.scala [hunk 1]
```diff
@@ -379,15 +367,18 @@ object Options extends OptionsPlatformSpecific {
               .validate(r._1, conf)
               .foldZIO(
                 _ => ZIO.succeed((r._1, Left(r._2))),
-                _ =>
+                _ => {
+                  // `uid` will only be None for Options.Empty. Which means the user would
+                  // have had to purposefully compose Options.Empty | otherArgument.
+                  val leftUid  = left.uid.getOrElse("???")
+                  val rightUid = right.uid.getOrElse("???")
```
Comment (kitlangton) [inline zio-cli/shared/src/main/scala/zio/cli/Options.scala:374]: Another option would be to make `uid` non-optional, and give it a value of `"Empty"` or something for `Options.Empty`.

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
Whoa, Kit sighting!! 😄 

Thanks for the PR! 🙏

**Comment by kitlangton** [comment]
@jdegoes I'm on vacation this week :D So I have time for OSS fun 🎉 This Algora thing provides a nice extra motivation boost ;P
